### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by emil2k** [tapeja/x#4]
We should come up with some rough overview of the design of the system, before we break up work and begin coding.

This can be placed in the main `README.md`.

---

Here is what I had in mind, for the first version.

You configure endpoints on the server using a simple YAML file, something like this in `config.yml` :

```yaml
---

thumbs:
  sizes:
    - square: 80
    - square: 200
  formats:
    - webp
    - png
    - jpeg
  store:
    - s3: mythumbs
    - aws_access_key: randomstuff
    - aws_secret_key: randomstuff

gallery:
  sizes:
    - max_width: 500
    - max: 1000
  formats:
    - jpeg
  store:
    - local: /mnt/gallery
```

Then you start the image processing server with the config file on some port :

```
$ ./x -c config.yml -p 8080
```

Now you would be able to send `POST` requests with image(s) directly to the endpoint `/v1/thumbs/` or `/v1/gallery/` and it will process them. It can respond with the SHA of the original image which will be used as an ID.

The images will be placed in the following locations on the configured data store :
```
{{ size key i.e. "square" }}/{{ size parameter i.e. "80" }}/{{ sha of the original image }}.{{ file format, i.e. "jpg" , "jpeg", "webp" }}
```

As images are processed there should be logs outputted that mention things like processing time, memory allocation ( when the image is fully decoded ), original size, output size, and maybe the load on the machine during processing. A `-o` flag on the server can specify the log path, default will be to standard output.

---

Is everybody ok with this? Does anybody have suggestions on how we should break up the work and proceed with development?
